### ISSUE TITLE
Remove redundant notifier for package download

### ISSUE THREAD

**Issue by DerRooster** [ansible-ThoTeam/nexus3-oss#181]
Hi,

The default behaviour during Nexus3 install ( https://github.com/ansible-ThoTeam/nexus3-oss/blob/master/tasks/nexus_install.yml) is to 

- download the package
- notify handler to stop nexus
- ..... 
- unarchive the package
- notify handler to stop nexus
- ..... 
- create symlinks 
- notify handler to stop nexus

Since the default location is /tmp which may get cleaned regularly, I propose to remove the first 2 handler notification. They seem redundant. 
Currently our nexus installation gets updated (e.g. config changes, additional repos) every few weeks. If the package has been removed from /tmp the nexus instance goes offline during the ansible run.

Thanks :-)

**Comment by zeitounator** [comment]
I'm very sorry for the looooong delay answering your question. I was totally off for quite a while and busy on tons of subjects on my return.

Regarding your specific problem, I am not going to change the role for that. If you run the role periodically against your nexus install, you should change the download location to somewhere the downloaded files will persist so that they don't get downloaded each time. This will save your bandwidth, speed up the role and solve your current problem all together.

Meanwhile, I will add a warning in the documentation.
