### ISSUE TITLE
get_url: CERTIFICATE_VERIFY_FAILED with valid system certificates #33580

### ISSUE THREAD

**Issue by dragon-bn** [ansible-ThoTeam/nexus3-oss#184]
Hello,

With the bug "https://github.com/ansible/ansible/issues/33580", i must modify the file "/tasks/nexus_install.yml" and force the variable "validate_certs: false" for the possibilty of download the nexus package.

Can you add the possibility to modify this variable : "validate_certs" in the file "defaults/main.yml" ?

Thanks you

Stephane

**Comment by zeitounator** [comment]
Hi @dragon-bn and sorry for the outrageous delay for this response.

May I ask you a little more background on how you hit this bug ? Are you downloading nexus from a local url after changing `nexus_download_url` ? Is that related to a custom CA or self signed cert you need to import (for custom url or internal proxy) ? This is just for my curiosity because it's the only cases I could think of. Since I am almost ready for a new release, I will add this there.

Thanks for your interest.
