### ISSUE TITLE
Add tags to specific part of it rather than running everything.

### ISSUE THREAD

**Issue by mateuszmroz93** [ansible-ThoTeam/nexus3-oss#271]
What do you think about adding specify tags to:
- ldap configurations
- content selectors
- privileges
- roles
- users 
- repositories

This will save time if someone wants to create a single thing like a repository or privileges.
Solution will be very useful in my case

ansible-thoteam.nexus3-oss/tasks/main.yml
`

    - name: Create/check roles
      include_tasks: call_script.yml
      vars:
        script_name: setup_roles_from_list
        args: "{{ nexus_roles }}"
      when: nexus_roles | length > 0
	  tags: add_roles
`

**Comment by zeitounator** [comment]
Hi and thanks for your interest,

I'm generally not really a fan of tags applied directly to specific tasks, moreover in a role. One of the drawbacks is that using the tag will play only the specific task, and I would then have to tag all the over mandatory tasks (like detecting version for a practical example) to run always or the role will fail. 

There is already an extra var switch `nexus_run_provisioning` you can use to totally bypass. I don't know how many roles, repos, users... you have, but since I started to modify the groovy scripts so that they accept lists rather than single elements, the time has dramatically lowered. I currently use the role on production with several hundred users/roles/repose and provisioning takes around a minute.

I'll leave open for now so that you or other can argue.

**Comment by zeitounator** [comment]
Without any returns at the moment and my schedule being rather busy on this role and other things, I will close this proposition for now
