### ISSUE TITLE
Provision a repository as offline 

### ISSUE THREAD

**Issue by ktreptow** [ansible-ThoTeam/nexus3-oss#290]
Is it possible to create an "offline" repository? The use-case would be to migrate an existing repository,  which is no longer being used, but has to be kept with all its artifacts,  from one nexus to another.

Would glady accept and appreciate any other way to do this. Thanks!

**Comment by zeitounator** [comment]
This is not supported by the role. As you will see in the [repo creation script](https://github.com/ansible-ThoTeam/nexus3-oss/blob/ce458dc05b8292ac8012071c7760be17e7dd5709/files/groovy/create_repos_from_list.groovy#L52), online is force to true on creation and never updated. I keep this as a feature request since it would be quite trivial to implement.
