### ISSUE TITLE
Support add SSL cerificate into nexus internal?

### ISSUE THREAD

**Issue by patsevanton** [ansible-ThoTeam/nexus3-oss#300]
Hello! Thanks for
I see in config
```
    nexus_public_scheme: https
```
But i don`t see where put ssl crt and key.
Support add SSL cerificate into nexus internal (like https://help.sonatype.com/repomanager3/system-configuration/configuring-ssl#ConfiguringSSL-ServingSSLDirectly) ?

**Comment by Goozimano** [comment]
Would like this enhancement as well.

**Comment by zeitounator** [comment]
This role does not manage certificates inside nexus repository (although it would be possible through the API). This is because most people/orgs (including me) are managing ssl termination with a reverse proxy or some other VIP infra in front of nexus.

The role includes a [basic optionnal reverse proxy setup](https://github.com/ansible-ThoTeam/nexus3-oss#reverse-proxy-setup) which is made just for that. To be perfectly transparent, I don't use this feature in production and create my own setup through a child role listing this one as a dependency.

Integrating ssl certs management is possible since there is a nexus API for that but would require some work. As you understand from the above, it is not on top of my todo list. But feel free to propose a PR if you wish.

Cheers.
