### ISSUE TITLE
Specify mode in "Setup Nexus data directory" task in nexus_install.yml

### ISSUE THREAD

**Issue by ashleykleynhans** [ansible-ThoTeam/nexus3-oss#302]
The latest version of Ansible has changed the default mode of files/directories that get created with the "file" module.
Since no "mode" option is specified in the task "Setup Nexus data directory", the default permissions of the data directory cause Nexus to fail to start.
Please could you update the task to specify a "mode" in order to fix this issue?

**Comment by vitkhab** [comment]
Looking into it. Seems issue is connected with https://github.com/ansible/ansible/issues/71200

`ansible-lint v4.3.5` show some [[208] File permissions unset or incorrect](https://ansible-lint.readthedocs.io/en/latest/default_rules.html#file-permissions-unset-or-incorrect) warnings

Also `molecule v3.0.8` with `ansible v2.10.1` fails converge on task
```
    TASK [nexus3-oss : Unpack Nexus download] **************************************
fatal: [nexus3-oss-default]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.unarchive) module: force Supported parameters include: attributes, creates, dest, exclude, extra_opts, group, keep_newer, list_files, mode, owner, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate_certs"}
```

It seems the role needs to be updated to support ansible v2.10

**Comment by vitkhab** [comment]
Now it's not a problem with newest versions of Ansible because change was reverted for [v2.8](https://github.com/ansible/ansible/pull/71233), [v2.9](https://github.com/ansible/ansible/pull/71232), [v2.10](https://github.com/ansible/ansible/pull/71236) and in [dev branch](https://github.com/ansible/ansible/pull/71231). Tested with `ansible v2.10.1`

In future Ansible releases this behavior is subject to change. So I'm still going to fix `ansible-lint` warnings.
