### ISSUE TITLE
LDAP config with User Password Attribute

### ISSUE THREAD

**Issue by serpa-dystematic** [ansible-ThoTeam/nexus3-oss#309]
Hey!

I'm trying to make a playbook which installs nexus and sets up the LDAP config.

I'm noticing that the only value my config is missing is the `Password Attribute` in the `User` section.

Is that something you **chose to keep out** of the LDAP groovy script, or **no one has asked for it** yet?

Thanks, and great role! 🙏

**Comment by zeitounator** [comment]
Hi.

I'm getting back to maintenance after a long pause for 2 main reason: 1) I was quite busy on other while the role was running like a charm on my side (deploying several times a month) and I had no special need for enhancements 2) the CI was down making reviewing PRs quite a pain (this has been fixed). Sorry for not getting in touch sooner.

----

The groovy script setting up ldap is basically a black box using undocumented and internal classes from Nexus code. It has broken on several occasion in the past and I'm even amazed it did not break again since you wrote your comment. This should all be refactored using the API, as all the other groovy scripts. Script might very well be dropped out of Nexus one day.

My long term project is to go full API and transform the role into a collection (if I ever have some more time than in the last 2 years...).

Too answer your direct question: you are the first one to raise this issue. I won't have time to work on that but I'm happy to review a PR if your feel like it.

Cheers.
