### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by jleonelion** [ansible-ThoTeam/nexus3-oss#310]
I'm working with a company that is strict on using Windows based servers.  This role provides a lot of capability to tune the NXRM OSS installation (much more so than others, I've seen).  Have there been talks to support running this role on a Windows server?  If not, would you be interested in having such support added to the role?

**Comment by zeitounator** [comment]
Hi and sorry for the delay.

No, there have been no talks to add windows support and I have no plans to add it to the role, nor any support for MacOS for example. That would add way too much complexity (to the current one that is already quite high). And since I do not use windows (appart from firing a 5 years old vm when I receive word documents scrambled in open office) and that the ci tools I use don't support it (freely as in free beer at least...), I would have no way to test and to maintain that implementation. Moreover, unless I have absolutely no other choice, I use and support only open source software and windows does not fall in that category.

I do have plans to one day split the role between installation and provisioning (but I have no precise schedule). This would enable to provision a pre-installed docker image (that could be deployed on any OS supporting docker) or any other instance of nexus installed by any mean. Although this is not really a production target, it is possible to run this role against a systemd or sysv enabled docker image based on one of the supported linux Oses. You can have a look at the images used by the molecule tests as a first glance if you want to try.

Thanks for you interest and cheers.

**Comment by jleonelion** [comment]
Are you sure?  I have finished the implementation and am happy to contribute back.  Otherwise, I will can just create a fork so anybody who needs to spin up NXRM under similar constraints has an easier life.

**Comment by zeitounator** [comment]
Well you can always create a PR and we will see if this goes through current CI so that at least it does not break the current supported OS. And I can then have a look at your changes to see how much complexity this brings in
