### ISSUE TITLE
Add support for nexus.vmoptions settings

### ISSUE THREAD

**Issue by AlexeiZenin** [ansible-ThoTeam/nexus3-oss#319]
Currently the Ansible role allows configuring JVM memory but it would be beneficial if we could add any arbitrary JVM option as shown here: https://help.sonatype.com/repomanager3/installation/configuring-the-runtime-environment

This is needed for hypertuning and adding javaagents (e.g. Datadog) to be able to do finer grain monitoring of the Nexus instance.

**Comment by zeitounator** [comment]
Hi.

I'm getting back to maintenance after a long pause for 2 main reason: 1) I was quite busy on other while the role was running like a charm on my side (deploying several times a month) and I had no special need for enhancements 2) the CI was down making reviewing PRs quite a pain (this has been fixed). Sorry for not getting in touch sooner.

----

I actually started maintenance over because we need to change the garbage collector to G1GC on our instance hence I implemented that feature in the PR I just linked. If you  look at the changes, it's a bit of a mess because I had to fix and revive the CI at the same time. But the new confit option in README should be quite understandable: https://github.com/ansible-ThoTeam/nexus3-oss/blob/main/README.md#nexus-jvm-setting. See as well the comments in defaults/main.yml.

Cheers.
