### ISSUE TITLE
Allow to configure pre-emptive authentication on repositories

### ISSUE THREAD

**Issue by Dropsu** [ansible-ThoTeam/nexus3-oss#351]
Currently there is no option to enable/disable "pre-emptive authentication" from the role. This would be a great addition since some remote repositories require that.
![image](https://user-images.githubusercontent.com/12545305/164680281-6cec62c0-dbea-42f2-be14-4b09d0c57a87.png)

**Comment by zeitounator** [comment]
Hi.  
  
I'm getting back to maintenance after a long pause for 2 main reason: 1) I was quite busy on other while the role was running like a charm on my side (deploying several times a month) and I had no special need for enhancements 2) the CI was down making reviewing PRs quite a pain (this has been fixed). Sorry for not getting in touch sooner.

I'm not able to find this option in current version of nexus (3.42.0) in any of the repository creation recipe I looked into. Is it in a specific type I missed? Moreover, this seems to be a rather confidential setting, probably to work around a remote repository misconfiguration. Can you please tell me in which cases this is a requirement? I might consider working on it if it looks rather critical.

My longer term project is to transform this role into a collection and drop as many groovy scripts as possible to move everything to the API which as long been totally stabilized since this role was created. My feeling is that this setting will have to wait until then.

Thanks in advance for your feedback and once again my apologies for this very late reply.

**Comment by zeitounator** [comment]
Without additional info for where to look for, closing this issue for now.
