### ISSUE TITLE
archive scripts action failing

### ISSUE THREAD

**Issue by gsagwan** [ansible-ThoTeam/nexus3-oss#365]
Hi,

We are getting below error while installing.

TASK [ansible-thoteam.nexus3-oss : Archive scripts] ********************************************************************************************************************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "expanded_paths": "", "msg": "Error, no source paths were found", "path": "/home/ec2-user/nexus-installation/roles/ansible-thoteam.nexus3-oss/files/groovy/*"}

ansible version | 2.9.5
ansible-thoteam.nexus3-oss | v2.4.14
Nexus installation version | 3.29.2-02
[ansible.log](https://github.com/ansible-ThoTeam/nexus3-oss/files/10259738/ansible.log)

**Comment by zeitounator** [comment]
To start with, I suggest you upgrade to a supported version of ansible which means as of today something higher or equal to 2.12 (see https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-changelogs for currently maintained versions). Ansible 2.9 has been deprecated for way over 2 year now which makes it a dinosaur compared to ansible development pace.

Since installing ansible is now only supported through pip, this lets you the options to install it on your system, for a specific user of inside a specific virtualenv which meant there are absolutely no blockers to install an up-to-date version. I did not dig into the changes to the `community.general.archive` module but there are changes this upgrade could fix the issue.

Next, I also suggest you upgrade to the lastest role version. The chances this fixes the issue are quite low but it is still a good move.

The nexus version here has no effect on the problem. Meanwhile, 3.28.2-02 is almost 2 years old and suffers from several critical security issues and bugs that have now been fixed (see https://help.sonatype.com/repomanager3/product-information/release-notes). So you should definitely upgrade to an up-to-date version as well. (although once again this not directly related to your problem).

If upgrading ansible (and the `community.general` collection) does not fix your problem, make sure that the role is installed correctly and contains the expected groovy files in `/home/ec2-user/nexus-installation/roles/ansible-thoteam.nexus3-oss/files/groovy/`. Also make sure that the files have the correct access right for the user running the playbook on the controller.

If the groovy files are correctly placed with the correct permissions, then the error message comes from this code in the module:

https://github.com/ansible-collections/community.general/blob/2b39470a774c28e26780e4e2e4cc9b998471da3c/plugins/modules/archive.py#L290-L296

The problem is that the module was not able to get any `expanded_paths` from the original `paths` passed as a parameter. I we look further, this variables gets its value by calling the function `expand_path` that can be found at the following place:

https://github.com/ansible-collections/community.general/blob/2b39470a774c28e26780e4e2e4cc9b998471da3c/plugins/modules/archive.py#L227-L238

I have at this moment absolutely no clue why this function could return an empty list for expanded paths from the initial `{{ role_path }}/files/groovy/*` passed as a parameter as you can see in the following code:
https://github.com/ansible-ThoTeam/nexus3-oss/blob/f836c34f5b99338ca12f05654632bcebacacca6b/tasks/nexus_install.yml#L551-L559

My absolute blind guess is that it could be linked to your python version and its implementation of the `glob` core lib (but I strongly doubt it's the case...) or that something on your platform is preventing python to find those groovy files.

In any case, I have never seen that error myself and it was never reported by other user. Moreover, I have no way to reproduce it.

I'll leave this ticket open for a while if you want to report back with more details once your have upgraded ansible and the role but I'm affraid I won't be able to do much.
