### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by brianveltman** [ansible-ThoTeam/nexus3-oss#391]
Looks like its been a while since this project got some activity.
If desired I can help out adding support for new Nexus features.

Besides the open issues and PR's I would like to know what features will have priority for the community, feel free to share

**Comment by zeitounator** [comment]
Hi and thanks for your interest.

This project is being maintained on a best effort basis. After a lot of work to make it stable a few years ago I basically only spend time when something is broken and needs to be fixed in order to deploy nexus at work (which is where the project started).

Since we've been deploying upgrades smoothly since last March, I did not make any commits nor incorporated new PRs. But I definitely will when I get time. And you look at the history a bit, you'll see I try to do this about once every year (out of breaking changes emergencies).

About priority on features, I'm not strictly applying scrum and safe here :), but I'll basically start with the ones having the best wsjf score. I will for sure drop the ones which are needing major refactoring or too many changes on the groovy scripts. Moreover, that maintenance work is getting harder as the free plan I use for CI tends to break more and more frequently as time passes by and I will have to fix it again (none of the current PR went through...)

Without being totally sure, early January will probably a good time for me to pick up some work on that repo.

**Comment by brianveltman** [comment]
Hi Olivier,

Thanks for reaching out to the community!

We have been using this Ansible role at work as well. We leverage our premium Sonatype support contract to incorporate changes and best practises to the role within our own internal git repository. After we have tested and deployed our changes, I file them as a PR on Github.

If you want I can help you out by moving the Travis pipelines to Github Actions to leverage the free CICD minutes for open source projects. And if necessary branch off and start working on some bigger refactoring topics, so people can decide if they want to upgrade to a new version of this role, or stick with the current branch.

**Comment by zeitounator** [comment]
Hi Brian,

I just checked and it seems that most CI run are blocked because of a "lack of email address validation" on Travis side. I have to check that. For time being, I'd like to keep the CI the way it is as I also got free minutes for open source project there which I can renew. Thanks.

**Comment by zeitounator** [comment]
Just to let you know that travis-ci is working as expected from my last test but there are several drawbacks in molecule (used to test the role) that I have to fix). Once this is done, I'll be able to rebase each PR so that the CI effectively run.

**Comment by brianveltman** [comment]
Great! Again, let me know if you need any help :-)

**Comment by zeitounator** [comment]
Not at this point but you might have some work once I rebase all current PRs ;) As you will see this started by a deprecation from molecule which does not support the lint verb anymore but this has gone way beyond. I can't beleive so many things have gone wrong... Stay tuned.

**Comment by brianveltman** [comment]
I am ready :-) In the meantime I have been working on some extra features we need on our side. Will create a PR for those changes somewhere later this month after I have tested it in our environments.

**Comment by zeitounator** [comment]
CI Fixed and all current PRs updated. I might be able to merge some of them sooner than I thought.

**Comment by zeitounator** [comment]
Christmas 2023 relase is out, Some more merges since then. I'll probably make a new release early January before what I suspect will be a new major version. I'll think over that on the Christmas break. Merry Christmas to everyone and see you next year.
