### ISSUE TITLE
flush_handlers in nexus_purge.yml is not skipped when purge!=true

### ISSUE THREAD

**Issue by BalazsGyarmati** [ansible-ThoTeam/nexus3-oss#94]
I have a role where I do things before and after I include this nexus3-oss role.
I have a notify in the before part for a handler, which should run after nexus3-oss role.
But this line:
https://github.com/ansible-ThoTeam/nexus3-oss/blob/289eb8fa4ab87cf54730f8738c2fd673379eb164/tasks/nexus_purge.yml#L9
is executed everytime, it doesn't respect the when statement, causing my handler to run too early.
```bash
TASK [ansible-ThoTeam.nexus3-oss : Check if SystemD service is installed] **********************************************************************************************************************************
ok: [10.x.x.x]

TASK [ansible-ThoTeam.nexus3-oss : Make sure nexus is stopped] *********************************************************************************************************************************************
skipping: [10.x.x.x]

RUNNING HANDLER [nexus : Remove RSA key] *******************************************************************************************************************************************************************
changed: [10.x.x.x]

TASK [ansible-ThoTeam.nexus3-oss : Purge Nexus] ************************************************************************************************************************************************************
skipping: [10.x.x.x] => (item=/nexus-data) 
skipping: [10.x.x.x] => (item=/opt/nexus-3.13.0-01) 
```

Unfortunately this is an ansible bug (or as they say a feature):
https://github.com/ansible/ansible/issues/41313
but maybe there is a way to change a code somehow to provide the same functionality + respect the when as well.

**Comment by zeitounator** [comment]
Hi and sorry for the very late reply. I was not able those last weeks to give this role the love it deserves :)

Regarding your specific problem... You are right, when statement on includes do not get copied over meta statements. But fixing this particular case will just move your problem forward.

The problem IMHO is the flush handlers itself and the fact that you register a handler outside of the role and would like to see it executed at the end of all tasks but it gets triggered to early for your needs.

Flush handler is used many times in this role (to stop/start nexus, wait for available ports... at precise steps) and not only in the purge file. Changing this would require to rethink the entire role skeleton. Moreover, introducing those flushes and using handlers was actually an enhancement compared to how the role was functioning in the past.

Since I did not have any other complains about the way handlers are triggered, I am not going to change anything for now. The only advice I can give is that, if you register handlers before this role is ran, you should make sure they can successfully run at any time during your play. Else you should consider registering your handler later or use a non-handler specific task that will run at your exactly at your convenience.
